---
title: "Codebook"
subtitle: "Project: Applicability of open science practices to completed research projects from different disciplines and research paradigms"
author: "Jürgen Schneider [0000-0002-3772-4198](https://orcid.org/0000-0002-3772-4198)"
affiliation: "University of Tübingen"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 3
    latex_engine: xelatex
---

# Packages & Setup

```{r setup, warning=F, message=F, error=F}
knitr::opts_chunk$set(
  warning = F, # don't show warnings during codebook generation
  message = F, # don't show messages during codebook generation
  error = F, # don't show errors during codebook generation
  echo = TRUE  # show R code
)

library(formr)
library(tidyverse)
library(codebook)

installed.packages()[names(sessionInfo()$otherPkgs), "Version"]
R.Version()
```

Now, we're preparing our data for the codebook.

```{r prepare_codebook}
formr_connect(keyring = "juergen")

codebook_data_0 <- formr_results(survey_name = 'osc_0')%>%
  dplyr::select(session, disc, prolific_pid, created) %>%
  dplyr::mutate(disc_broad = str_sub(disc, 1, 3),
                disc = case_when(
                  disc == "nat01" ~	"'nat' - Mathematics", 
                  disc == "nat02" ~	"'nat' - Computer and Information Science", 
                  disc == "nat03" ~	"'nat' - Physical Sciences", 
                  disc == "nat04" ~	"'nat' - Chemical Sciences", 
                  disc == "nat05" ~	"'nat' - Earth and related environmental sciences", 
                  disc == "nat06" ~	"'nat' - Biological Sciences", 
                  disc == "nat07" ~	"'nat' - Other natural sciences", 
                  disc == "eng01" ~	"'eng' - Civil engineering", 
                  disc == "eng02" ~	"'eng' - Electric., electron., informat. engineering", 
                  disc == "eng03" ~	"'eng' - Mechanical engineering", 
                  disc == "eng04" ~	"'eng' - Chemical engineering", 
                  disc == "eng05" ~	"'eng' - Materials engineering", 
                  disc == "eng06" ~	"'eng' - Medical engineering", 
                  disc == "eng07" ~	"'eng' - Environmental engineering", 
                  disc == "eng08" ~	"'eng' - Environmental biotechnology", 
                  disc == "eng09" ~	"'eng' - Industrial Biotechnology", 
                  disc == "eng10" ~	"'eng' - Nanotechnology", 
                  disc == "eng11" ~	"'eng' - Other engineering and technologies", 
                  disc == "med01" ~	"'med' - Basic medicine", 
                  disc == "med02" ~	"'med' - Clinical medicine", 
                  disc == "med03" ~	"'med' - Health Sciences", 
                  disc == "med04" ~	"'med' - Health biotechnology", 
                  disc == "med05" ~	"'med' - Other medical sciences", 
                  disc == "agr01" ~	"'agr' - Agriculture, forestry, and fisheries", 
                  disc == "agr02" ~	"'agr' - Animal and dairy science", 
                  disc == "agr03" ~	"'agr' - Veterinary science", 
                  disc == "agr04" ~	"'agr' - Other agricultural sciences", 
                  disc == "soc01" ~	"'soc' - Psychology", 
                  disc == "soc02" ~	"'soc' - Economics and business", 
                  disc == "soc03" ~	"'soc' - Educational Sciences", 
                  disc == "soc04" ~	"'soc' - Sociology", 
                  disc == "soc05" ~	"'soc' - Law", 
                  disc == "soc06" ~	"'soc' - Political Sciences", 
                  disc == "soc07" ~	"'soc' - Social and economic geography", 
                  disc == "soc08" ~	"'soc' - Media and Communications", 
                  disc == "soc09" ~	"'soc' - Other social Sciences", 
                  disc == "hum01" ~	"'hum' - History and archeology", 
                  disc == "hum02" ~	"'hum' - Languages and literature", 
                  disc == "hum03" ~	"'hum' - Philosophy, ethics and religion", 
                  disc == "hum04" ~	"'hum' - Art (arts, history of & performing arts, music)", 
                  disc == "hum05" ~	"'hum' - Other humanities"),
                disc = as.factor(disc))


codebook_data_1 <- formr_results(survey_name = 'osc')%>%
  dplyr::select(-created)



codebook_data <- left_join(codebook_data_1, codebook_data_0, by = "session") %>%
  dplyr::filter(nchar(prolific_pid)>20 & !is.na(finished)) %>%
  dplyr::select(-prolific_pid, -finished)


# Updating Variable labels
var_label(codebook_data$osp_prp) <- "__Publicly sharing project plans to encourage feedback and collaboration.__  
Researchers make their project plans publicly available at an early stage (e.g., on social media, websites) to optimize the study design through feedback and to encourage collaboration.  
_'Open Collaboration'_"
var_label(codebook_data$osp_pre) <- "__Preregistering study plans__  
Researchers submit important information about their study (for example: research rationale, hypotheses, design and analytic strategy) to a public registry before beginning the study.  
'Preregistration'"
var_label(codebook_data$osp_met) <- "__Publicly sharing the methodology of the research process__  
Researchers describe methods, procedures and instruments that are used in the process of knowledge generation and make them publicly available.  
'Open Methodology'"
var_label(codebook_data$osp_sof) <- "__Using Open file formats and research software__  
Researchers use software (for analysis, simulation, visualization, etc.) as well as file formats that grant permission to access, re-use, and redistribute material with few or no restrictions.  
'Open File Formats and Research Software'"
var_label(codebook_data$osp_mat) <- "__Publicly sharing research materials__  
Researchers share research materials, for example, biological and geological samples, instruments for measurement or stimuli used in the study.  
'Open Materials'"
var_label(codebook_data$osp_cod) <- "__Publicly sharing data analyses__  
Researchers make the procedure of the data analyses and their scripts ('code') publicly available so that others are able to reach the same results as are claimed in scientific outputs.  
'Open Code / Open Script'"
var_label(codebook_data$osp_dat) <- "__Publicly sharing research data__  
Researchers publicly provide the data generated in the research process free of cost and accessible so that if can be used, reused and distributed provided that the data source is attributed.  
'Open Data'"
var_label(codebook_data$osp_oer) <- "__Generating Open Educational Resources__  
Researchers produce and release teaching, learning and research materials in any medium that reside in the public domain or have been released under an open license that permits no-cost access, use, adaptation and redistribution by others with no or limited restrictions. Open educational resources include full courses, course materials, modules, textbooks, streaming videos, tests, images, software, and any other tools, materials, or techniques used to support access to knowledge.  
'Open Educational Resources'"
var_label(codebook_data$osp_opr) <- "__Deciding for openness in the peer review process__  
Researchers opt for some kind of openness in the peer review process, including making reviewer or author identities open, publishing review reports or enabling a broader community to participate in the process.  
'Open Peer Review'"
var_label(codebook_data$osp_oap) <- "__Publishig open access__  
Researchers publish their research paper online, free of cost with free reusability regarding copyright restrictions. This involves any form of open access (preprints, gold and hybrid open access, etc.).  
'Open Access'"
var_label(codebook_data$osp_oso) <- "__Providing open source code of software__  
Researchers make source code for a piece of software that was developed in the research process publicly available, along with an open source license permitting reuse, adaptation, and further distribution.  
'Open Scource'"
var_label(codebook_data$osp_sco) <- "__Communicating research results to nonacademics__  
Researchers use appropriate skills, media, activities, and dialogue to produce one or more of the following personal responses to science: Awareness, Enjoyment, Interest, Opinions, Understanding. Science communication may involve science practitioners, mediators, and other members of the general public, either peer-to-peer or between groups.  
'Science Communication'"
var_label(codebook_data$osp_cit) <- "__Involving the non-academic public in the research process__  
The non-academic public is involved in the process of scientific research – whether in community-driven research or global investigations. Citizens do scientific work—often working together with experts or scientific institutions. They support the generation of relevant research questions, the collection, analysis or description of research data and make a valuable contribution to science. 'Citizen Science'"
var_label(codebook_data$para) <- "__Research paradigm__  
What was the projects primary research interest and design?"
var_label(codebook_data$disc) <- "__Discipline.__  
On the next page you will answer questions regarding a previous research project. To which discipline is this research project most closely related?"

```


# Codebook

```{r codebook}
codebook(codebook_data)
```